version: '3.1'

services:
  db:
    image: postgres:10
    restart: always
    user: root
    environment:
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: cacartag
      POSTGRES_PASSWORD: alexis
    volumes:
      - /home/chris/Documents/PostgresFiles:/var/lib/postgresql/data/pgdata
    ports:
      - 5420:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      